import { Box } from "@mui/system";
import BusinessList from "../../components/business/list";
import MainContent from "../../components/container/MainContent";
import styles from "./index.module.css";

const DUMMY = {
  error: false,
  result: {
    id: 7,
    name: "Twirly Laundry",
    email: "test@ordering.co",
    slug: "thetwirlylaundry",
    schedule: [
      {
        enabled: true,
        lapses: [
          {
            open: {
              hour: 0,
              minute: 0,
            },
            close: {
              hour: 23,
              minute: 59,
            },
          },
        ],
      },
      {
        enabled: true,
        lapses: [
          {
            pen: {
              our: 0,
              minute: 0,
            },
            lose: {
              our: 23,
              minute: 59,
            },
          },
        ],
      },
      {
        enabled: true,
        lapses: [
          {
            open: {
              hour: 0,
              minute: 0,
            },
            close: {
              hour: 23,
              minute: 59,
            },
          },
        ],
      },
      {
        enabled: true,
        lapses: [
          {
            open: {
              hour: 0,
              minute: 0,
            },
            close: {
              hour: 23,
              minute: 59,
            },
          },
        ],
      },
      {
        enabled: true,
        lapses: [
          {
            open: {
              hour: 0,
              minute: 0,
            },
            close: {
              hour: 23,
              minute: 59,
            },
          },
        ],
      },
      {
        enabled: true,
        lapses: [
          {
            open: {
              hour: 0,
              minute: 0,
            },
            close: {
              hour: 23,
              minute: 59,
            },
          },
        ],
      },
      {
        enabled: true,
        lapses: [
          {
            open: {
              hour: 0,
              minute: 0,
            },
            close: {
              hour: 23,
              minute: 59,
            },
          },
        ],
      },
    ],
    description: "",
    about: "",
    logo: "https://res.cloudinary.com/ordering/image/upload/v1534196961/ak4o8bfgxcpoue0fx1xa.jpg",
    header:
      "https://res.cloudinary.com/ordering/image/upload/v1534196946/dl8r7vye0zoilnuevors.jpg",
    phone: "12382348",
    cellphone: "2382348",
    owner_id: 1,
    city_id: 1,
    address: "19 Grand Street, New York, NY, USA",
    address_notes: null,
    zipcode: null,
    location: {
      lat: 40.7228702,
      lng: -74.00508250000001,
      zipcode: -1,
      zoom: 15,
    },
    featured: true,
    timezone: "America/New_York",
    currency: "USD",
    food: false,
    alcohol: false,
    groceries: false,
    laundry: true,
    use_printer: false,
    printer_id: null,
    minimum: 0,
    delivery_price: 0,
    always_deliver: false,
    tax_type: 2,
    tax: 0,
    delivery_time: "0:0",
    pickup_time: "0:0",
    service_fee: 0,
    fixed_usage_fee: 0,
    percentage_usage_fee: 0,
    enabled: true,
    checkoutfields: {
      name: {
        name: "Name",
        type: "text",
        required: true,
        enabled: true,
      },
      lastname: {
        name: "Last Name",
        type: "text",
        required: false,
        enabled: false,
      },
      email: {
        name: "Email",
        type: "text",
        required: true,
        enabled: true,
      },
      address: {
        name: "Address",
        type: "text",
        required: true,
        enabled: true,
      },
      address_notes: {
        name: "Address notes",
        type: "text",
        required: false,
        enabled: true,
      },
      driver_tip: {
        name: "Driver tip",
        type: "text",
        required: false,
        enabled: true,
      },
      coupon: {
        name: "Coupon",
        type: "text",
        required: false,
        enabled: true,
      },
      mobile_phone: {
        name: " Mobile phone",
        type: "text",
        required: false,
        enabled: true,
      },
      zipcode: {
        name: "Zipcode",
        type: "text",
        required: false,
        enabled: false,
      },
      city_dropdown_option: {
        name: "City and dropdown option",
        type: "select",
        required: false,
        enabled: false,
      },
    },
    reviews: {
      reviews: [],
      quality: 0,
      delivery: 0,
      service: 0,
      package: 0,
      total: 0,
    },
    open: true,
    today: {
      enabled: true,
      lapses: [
        {
          open: {
            hour: 0,
            minute: 0,
          },
          close: {
            hour: 23,
            minute: 59,
          },
        },
      ],
    },
    categories: [
      {
        id: 102,
        business_id: 7,
        name: "Repair & Alteration",
        image:
          "https://res.cloudinary.com/ordering2/image/upload/v1539099254/aj9tqgx3aw910id9nwqa.jpg",
        rank: 6,
        enabled: true,
        products: [
          {
            id: 474,
            name: "Zip Replacement (Per Inch)",
            price: 3.5,
            description: "",
            images:
              "https://res.cloudinary.com/ordering/image/upload/v1534197282/cwppfw1d8xeej9t1ijab.jpg",
            sku: null,
            category_id: 102,
            inventoried: false,
            quantity: 0,
            featured: false,
            enabled: true,
            extras: [],
            gallery: [],
            ingredients: [],
          },
          {
            id: 475,
            name: "Take Up Trousers",
            price: 14,
            description: "",
            images:
              "https://res.cloudinary.com/ordering/image/upload/v1534167378/fzy5bgiazrvxhyryawmq.png",
            sku: null,
            category_id: 102,
            inventoried: false,
            quantity: 0,
            featured: false,
            enabled: true,
            extras: [],
            gallery: [],
            ingredients: [],
          },
          {
            id: 476,
            name: "Skirt / Dress Length Alteration",
            price: 14,
            description: "",
            images:
              "https://res.cloudinary.com/ordering/image/upload/v1534167370/vdjgnlwuculftkq1mliv.png",
            sku: null,
            category_id: 102,
            inventoried: false,
            quantity: 0,
            featured: false,
            enabled: true,
            extras: [],
            gallery: [],
            ingredients: [],
          },
        ],
      },
      {
        id: 101,
        business_id: 7,
        name: "Duvets",
        image:
          "https://res.cloudinary.com/ordering2/image/upload/v1539099249/cvoez7vypep6suncgzt3.png",
        rank: 5,
        enabled: true,
        products: [
          {
            id: 477,
            name: "Feather Duvet (Single)",
            price: 18.95,
            description: "",
            images:
              "https://res.cloudinary.com/ordering/image/upload/v1534197144/yr05ybzcmfliedxrgrg4.jpg",
            sku: null,
            category_id: 101,
            inventoried: false,
            quantity: 0,
            featured: false,
            enabled: true,
            extras: [],
            gallery: [],
            ingredients: [],
          },
          {
            id: 478,
            name: "Blanket",
            price: 18,
            description: "",
            images:
              "https://res.cloudinary.com/ordering/image/upload/v1534167293/vua77kk3dewamvvxoba6.png",
            sku: null,
            category_id: 101,
            inventoried: false,
            quantity: 0,
            featured: false,
            enabled: true,
            extras: [],
            gallery: [],
            ingredients: [],
          },
          {
            id: 479,
            name: "Feather Duvet (Double)",
            price: 30,
            description: "",
            images:
              "https://res.cloudinary.com/ordering/image/upload/v1534197150/munk3uzn2c1hizxnp3nj.jpg",
            sku: null,
            category_id: 101,
            inventoried: false,
            quantity: 0,
            featured: false,
            enabled: true,
            extras: [],
            gallery: [],
            ingredients: [],
          },
        ],
      },
      {
        id: 100,
        business_id: 7,
        name: "Wash & Fold",
        image:
          "https://res.cloudinary.com/ordering2/image/upload/v1539099241/aljkf8flsfjpjox3mc8y.png",
        rank: 4,
        enabled: true,
        products: [
          {
            id: 480,
            name: "Medium Laundry Bag",
            price: 15,
            description: "",
            images:
              "https://res.cloudinary.com/ordering/image/upload/v1534167208/zmuitmtbyog8afa6osfp.png",
            sku: null,
            category_id: 100,
            inventoried: false,
            quantity: 0,
            featured: false,
            enabled: true,
            extras: [],
            gallery: [],
            ingredients: [],
          },
          {
            id: 481,
            name: "Large Laundry Bag",
            price: 20,
            description: "",
            images:
              "https://res.cloudinary.com/ordering/image/upload/v1534167217/kmoi8uejjmc0uyzuepvy.png",
            sku: null,
            category_id: 100,
            inventoried: false,
            quantity: 0,
            featured: false,
            enabled: true,
            extras: [],
            gallery: [],
            ingredients: [],
          },
          {
            id: 482,
            name: "Small Laundry Bag",
            price: 13,
            description: "",
            images:
              "https://res.cloudinary.com/ordering/image/upload/v1534167223/kqnzygjm1axchbwleqnr.png",
            sku: null,
            category_id: 100,
            inventoried: false,
            quantity: 0,
            featured: false,
            enabled: true,
            extras: [],
            gallery: [],
            ingredients: [],
          },
        ],
      },
      {
        id: 98,
        business_id: 7,
        name: "Shirts",
        image:
          "https://res.cloudinary.com/ordering2/image/upload/v1539099223/awelrxjbmlgbyxn5gxdk.png",
        rank: 2,
        enabled: true,
        products: [
          {
            id: 483,
            name: "Shirt (On Hanger)",
            price: 2.25,
            description: "",
            images:
              "https://res.cloudinary.com/ordering/image/upload/v1534167092/f3vqh8cmr5lri34ejtkn.png",
            sku: null,
            category_id: 98,
            inventoried: false,
            quantity: 0,
            featured: false,
            enabled: true,
            extras: [],
            gallery: [],
            ingredients: [],
          },
          {
            id: 484,
            name: "Shirt (Linen)",
            price: 3.99,
            description: "",
            images:
              "https://res.cloudinary.com/ordering/image/upload/v1534167110/ryiaw1kdggvxzdga8igr.png",
            sku: null,
            category_id: 98,
            inventoried: false,
            quantity: 0,
            featured: false,
            enabled: true,
            extras: [],
            gallery: [],
            ingredients: [],
          },
          {
            id: 485,
            name: "Shirt (Hand Finished)",
            price: 3,
            description: "",
            images:
              "https://res.cloudinary.com/ordering/image/upload/v1534167081/gbm9h4fxhfl2lag0p4ga.png",
            sku: null,
            category_id: 98,
            inventoried: false,
            quantity: 0,
            featured: false,
            enabled: true,
            extras: [],
            gallery: [],
            ingredients: [],
          },
          {
            id: 486,
            name: "Shirt (Folded)",
            price: 3,
            description: "",
            images:
              "https://res.cloudinary.com/ordering/image/upload/v1534167103/bfu82ufhmh6xqgzxuioe.png",
            sku: null,
            category_id: 98,
            inventoried: false,
            quantity: 0,
            featured: false,
            enabled: true,
            extras: [],
            gallery: [],
            ingredients: [],
          },
          {
            id: 487,
            name: "Shirt",
            price: 2.25,
            description: "",
            images:
              "https://res.cloudinary.com/ordering/image/upload/v1534167067/wmpfkcedo4y2kwxcamve.png",
            sku: null,
            category_id: 98,
            inventoried: false,
            quantity: 0,
            featured: false,
            enabled: true,
            extras: [],
            gallery: [],
            ingredients: [],
          },
        ],
      },
      {
        id: 97,
        business_id: 7,
        name: "Laundry",
        image:
          "https://res.cloudinary.com/ordering2/image/upload/v1539099221/yrlnpdo6b2hllgbhrpit.png",
        rank: 1,
        enabled: true,
        products: [
          {
            id: 488,
            name: "Dress (Everyday)",
            price: 11,
            description: "",
            images:
              "https://res.cloudinary.com/ordering/image/upload/v1534166759/cy89045kwlzzur3fmvea.png",
            sku: null,
            category_id: 97,
            inventoried: false,
            quantity: 0,
            featured: false,
            enabled: true,
            extras: [],
            gallery: [],
            ingredients: [],
          },
          {
            id: 489,
            name: "Blouse",
            price: 5.95,
            description: "",
            images:
              "https://res.cloudinary.com/ordering/image/upload/v1534166711/g7uhotajyugqpfrejopz.png",
            sku: null,
            category_id: 97,
            inventoried: false,
            quantity: 0,
            featured: false,
            enabled: true,
            extras: [],
            gallery: [],
            ingredients: [],
          },
          {
            id: 490,
            name: "Dress with Trim",
            price: 18,
            description: "",
            images:
              "https://res.cloudinary.com/ordering/image/upload/v1534166808/k7lyesjy78o2be46ok0e.png",
            sku: null,
            category_id: 97,
            inventoried: false,
            quantity: 0,
            featured: false,
            enabled: true,
            extras: [],
            gallery: [],
            ingredients: [],
          },
        ],
      },
      {
        id: 99,
        business_id: 7,
        name: "Dry Cleaning",
        image:
          "https://res.cloudinary.com/ordering2/image/upload/v1539099226/u9merzxfmkmywyrxtkni.jpg",
        rank: 3,
        enabled: true,
        products: [
          {
            id: 492,
            name: "3 Piece Morning Suit",
            price: 17.5,
            description: "",
            images:
              "https://res.cloudinary.com/ordering/image/upload/v1534197194/p5jxvp76b5tbuq6ao1p0.jpg",
            sku: null,
            category_id: 99,
            inventoried: false,
            quantity: 0,
            featured: false,
            enabled: true,
            extras: [],
            gallery: [],
            ingredients: [],
          },
          {
            id: 494,
            name: "2 Piece Morning Suit",
            price: 25,
            description: "",
            images:
              "https://res.cloudinary.com/ordering/image/upload/v1534197191/lqtdyj4paebez9kfoxw5.jpg",
            sku: null,
            category_id: 99,
            inventoried: false,
            quantity: 0,
            featured: false,
            enabled: true,
            extras: [],
            gallery: [],
            ingredients: [],
          },
          {
            id: 495,
            name: "Coat Wool",
            price: 15.5,
            description: "",
            images:
              "https://res.cloudinary.com/ordering/image/upload/v1534197200/bihvkrgxlamgqf2v9noc.jpg",
            sku: null,
            category_id: 99,
            inventoried: false,
            quantity: 0,
            featured: false,
            enabled: true,
            extras: [],
            gallery: [],
            ingredients: [],
          },
          {
            id: 496,
            name: "Cardigan / Jumpers",
            price: 6.95,
            description: "",
            images:
              "https://res.cloudinary.com/ordering/image/upload/v1534197197/ajaydtk9fotxpsbrelm3.jpg",
            sku: null,
            category_id: 99,
            inventoried: false,
            quantity: 0,
            featured: false,
            enabled: true,
            extras: [],
            gallery: [],
            ingredients: [],
          },
          {
            id: 497,
            name: "Dress Long",
            price: 16,
            description: "",
            images:
              "https://res.cloudinary.com/ordering/image/upload/v1534197207/dubap3kszxafrnnrppan.jpg",
            sku: null,
            category_id: 99,
            inventoried: false,
            quantity: 0,
            featured: false,
            enabled: true,
            extras: [],
            gallery: [],
            ingredients: [],
          },
          {
            id: 498,
            name: "Dress (Silk, Linen, Velvet)",
            price: 14,
            description: "",
            images:
              "https://res.cloudinary.com/ordering/image/upload/v1534197204/j5ud3pbtxbudwdso3oso.jpg",
            sku: null,
            category_id: 99,
            inventoried: false,
            quantity: 0,
            featured: false,
            enabled: true,
            extras: [],
            gallery: [],
            ingredients: [],
          },
        ],
      },
    ],
    valid_service: true,
    num_zones: 0,
    gallery: [],
    offers: [],
    city: {
      id: 1,
      name: "New York",
      country_id: 1,
      administrator_id: 6,
      enabled: true,
      country: {
        id: 1,
        name: "United States",
        enabled: true,
      },
    },
    webhooks: [],
    paymethods: [
      {
        id: 9,
        paymethod_id: 1,
        business_id: 7,
        sandbox: false,
        enabled: true,
        created_at: "2018-10-06 18:18:26",
        updated_at: "2018-10-06 18:18:26",
        data: {},
        paymethod: {
          id: 1,
          name: "Cash",
          gateway: "cash",
          enabled: true,
          deleted_at: null,
          created_at: "2018-10-06 18:18:25",
          updated_at: "2018-10-06 18:18:25",
        },
      },
    ],
  },
};

const BusinessPage = () => {
  return (
    <Box className={styles.container}>
      <BusinessList/>
    </Box>
  );
};

export default BusinessPage;
